blog/urls.py
from django.urls import path
from .views import (

    create_blog_view,
    blog_view,
    CatListView,
    edit_blog_view,
    comment_view,
    delete_post,
    DetailPostView,
    category_list,
    commet_reply_view

)

app_name = 'blog'

urlpatterns = [

    path('create/', create_blog_view, name='create'),
    path('<slug>/edit', edit_blog_view, name='edit'),
    path('category/<category>', CatListView.as_view(), name='category'),
    path('get/category/', category_list, name='category_list'),
    path('<slug:slug>/', DetailPostView.as_view(), name='details'),
    path('comment', comment_view, name='comment'),
    path('comment/reply', commet_reply_view, name='comment_reply'),
    path('delete', delete_post, name='delete_post'),
    path('', blog_view, name='blog'),
]

fitness/urls.py
from django.urls import path
from .views import index_view, search_view, faq_views,  recommendation_view

app_name = "fitness"

urlpatterns = [
    path("", index_view, name="index"),
    path("search/", search_view, name="search"),
    path("faqs/", faq_views, name="faqs"),
    path("recommendation/", recommendation_view, name="recommendation"),
]

product/urls.py
from django.urls import path
from .views import (
    product_view,
    TagListView,
    DetailProductView,
)

app_name = 'product'

urlpatterns = [
    path('tag/<tag>', TagListView.as_view(), name='tag'),
    path('<slug:slug>/', DetailProductView.as_view(), name='detail'),
    path('', product_view, name='product'),
]

site_src/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('account/', include('allauth.urls')),
    path('account/', include('user.urls')),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('', include('fitness.urls')),
    path('blog/', include('blog.urls')),
    path('product/', include('product.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/snippets/footer.html
{% load static %}

<footer class="p-5">

    <div class="container">
        <div class="row align-items-center">
            <div class="col-sm-6 fs-6">
                <p class="fw-bold py-0">TrendFitness</p>
                <p class="py-0 mt-0">Info@domain.com</p>
            </div>
            <div class="col-sm-6">
                <form action="">
                    <div class="form-group">
                        <label for="#subscribe" class="fw-bold fs-6 py-3">Subscribe to our newsletter</label>
                        <div class="input-group mb-3">
                            <input id="subscribe" type="email" class="form-control" placeholder="Enter your email address">
                            <button class="btn btn-outline-danger" type="button">Subscribe</span>
                        </div>
                    </div>
                    
                </form>
            </div>
        </div>
    </div>

    <div class="container">
        <div class="row">
            <div class="col fs-6">
                <ul class="list-unstyled fw-bold">
                    <li class="footer-list"><a href="" >About us</a></li>
                    <li class="footer-list"><a href="" >Top Earners</a></li>
                    <li class="footer-list"><a href="" >Terms & Conditions</a></li>
                    <li class="footer-list"><a href="" >Contact Us</a></li>
                </ul>
            </div>

            <div class="col fs-6">
                <ul class="list-unstyled fw-bold">
                    <li class="footer-list"><a href="{% url 'fitness:faqs' %}" >FAQs</a></li>
                    <li class="footer-list"><a href="" >How to Refer</a></li>
                    <li class="footer-list"><a href="" >Privacy Policy</a></li>
                </ul>
            </div>
        </div>
    </div>

    <div class="my-0 pt-2 text-center text-small">
        <p class="mb-1">© <span id="footer-date"></span> TrendFitness</p>
        <ul class="list-inline">
          <li class="list-inline-item"><a href="#">Privacy</a></li>
          <li class="list-inline-item"><a href="#">Terms</a></li>
          <li class="list-inline-item"><a href="#">Support</a></li>
        </ul>
      </div>
</footer>

templates/snippets/header.html
{% load static %}

<nav class="p-1 navbar navbar-expand-md row align-items-center">
    <a href="{% url 'fitness:index' %}" class="col-md-4 d-flex justify-content-md-start justify-content-center align-items-center" style="text-decoration: none;">
        <img src="{% static 'img/logo.jpeg' %}" width="50" alt="TrendsFitness Logo">
        <h5>TRENDFITNESS</h5>
    </a>

    <div class="navbar-dark d-md-none d-flex justify-content-center">
        <button class="navbar-toggler nav_toggle_btn collapsed" type="button" data-bs-toggle="modal" data-bs-target="#nav-menu" aria-controls="navbarsExample06" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    </div>
    
    <ul class="col-md-8 d-flex justify-content-between align-items-center fs-lg-3">
        <li><i class="fa-solid fa-location-dot"></i> Location</li>
        <li><i class="fa fa-phone-volume"></i> Call</li>
        <li><i class="fa-solid fa-envelope"></i> mail@domain.com</li>
    </ul>
</nav>
<div class="section1">
    <div class="d-none d-md-block">
        <div class="row justify-content-center mt-0">
            <div class="col-9 bg-yellow mt-0">
                <ul class="d-flex justify-content-between align-items-center fw-bold h6 pt-3 pb-2 px-2">
                    <li class="nav-item">
                        <a class="navbar-brand" href="{% url 'fitness:index' %}">Home</a>
                    </li>
                    <li class="nav-item">
                        <a class="navbar-brand" href="{% url 'blog:blog' %}">Blog</a>
                    </li>
                    <li class="nav-item">
                        <a class="navbar-brand" href="{% url 'product:product' %}">Product</a>
                    </li>
                    <li class="nav-item">
                        <a class="navbar-brand" href="#">Service</a>
                    </li>
                    {% if not request.user.is_authenticated %}
                    <li class="nav-item">
                        <a class="navbar-brand" href="{% url 'account_login' %}">Login</a>
                    </li>
                    <li class="nav-item">
                        <a class="navbar-brand" href="{% url 'account_signup' %}">Sign up</a>
                    </li>
                    {% else %}
                    {% if request.user.is_admin %}
                    <li class="nav-item">
                        <a class="navbar-brand" href="/admin/">Admin</a>
                    </li>
                    {% endif %}
                    <li class="nav-item">
                        <a class="navbar-brand" href="{% url 'account_logout' %}">Logout</a>
                    </li>                    
                    {% endif %}
                    <li id="search_toggle" class="navbar-toggler nav_toggle_btn collapsed" type="button" data-bs-toggle="modal" data-bs-target="#nav-menu" aria-controls="navbarsExample06" aria-expanded="false" aria-label="Toggle navigation">
                        <i class="fa fa-search"></i>
                    </li>
                </ul>
            </div>
        </div>
    </div>
    
    
    {% if page == 'home' %}
    <section class="pt-5 mb-0 container pb-5">
        <div class="d-grid text-center justify-content-center align-items-center text-light">
            <h1 >Welcome to TrendFitness</h1>
            <p class="fs-4">
                Trend Fitness is a web application dedicated to providing professional fitness advice which will include a range from fitness plans to diet plans catered to every individual needs.
                Embark on a transformative journey towards a healthier lifestyle. Discover personalized training programs designed to meet their unique fitness needs.
            </p>
            <a href="{% url 'account_signup' %}" class="btn btn-danger col-6 col-md-4  align-items-center justify-content-center fw-bold fs-4 mx-auto">Get Started</a>
        </div>
    </section>
    {% endif %}
</div>

templates/snippets/message.html
<style>
    .alert-error{
        background-color: #d86e79;
        color: #442428;
    }
</style>

<div id="msg">
    {% if messages %}
    <div class="container" class="mt-5">
    <div>
        {% for message in messages %}
        <div class="d-flex justify-content-center text-center alert alert-{{message.tags}} m-2" role="alert">
            <p class="fw-bold fs-4 mb-0 mx-2">{{message.tags | title}}!</p>
            <p class="fs-4 mb-0">{{message}}</p>
        </div>
        {% endfor %}
    </div>
    </div>
    {% endif %}
</div>

<script>
    setTimeout(function(){
        if ($('#msg').length > 0){
            $('#msg').remove();
        }
    }, 5000)
</script>

templates/snippets/modal.html
<div class="modal navbar-collapse collapse d-md-none" id="nav-menu" tabindex="-1" aria-labelledby="nav-menu" aria-modal="true" role="dialog">
	<div class="modal-dialog modal-fullscreen" style="height:100vh; width:70vw; color:var(--yello);">
		<div class="modal-content" style="background-color: var(--black)">
			
				<div class="modal-body">
					<div id="sidebarMenu" class="">
						<div class="nav_head ms-auto">
							<ul class="me-auto mb-2 mb-lg-0">
								<li class="nav-item mb-4">
									<form id="search" action="{% url 'fitness:search' %}" method="get" class="">
										<div class="form-group d-flex justify-content-center align-items-center">
											<input type="text" name="q" id="q" class="form-control bg-yellow rounded-5" placeholder="Search" required>
											<button type="submit" class="fas fa-search"></button>
										</div>										
									</form>
								</li>
								
								<li class="nav-item mb-4">
									<a class="navbar-brand ms-3" href="{% url 'fitness:index' %}">
										<i class="fa-solid fa-home me-2"></i>
										Home
									</a>
								</li>
								<li class="nav-item mb-4">
									<a class="navbar-brand ms-3" href="{% url 'blog:blog' %}">
										<i class="fa-solid fa-blog me-2"></i>
										Blog
									</a>
								</li>

								<li class="nav-item mb-4">
									<a class="navbar-brand ms-3" href="{% url 'product:product' %}">
										<i class="fa-solid fa-blog me-2"></i>
										Product
									</a>
								</li>

								{% if not request.user.is_authenticated %}
								
								<li class="nav-item mb-4">
									<a class="navbar-brand ms-3" href="{% url 'account_login' %}">
										<i class="fa-solid fa-right-to-bracket me-2"></i>
										Login
									</a>
								</li>
								<li class="nav-item mb-4">
									<a class="navbar-brand ms-3" href="{% url 'account_signup' %}">
										<i class="fa-solid fa-user-plus me-2"></i>
										Sign up
									</a>
								</li>
								{% else %}
								<li class="nav-item mb-4">
									<a class="navbar-brand ms-3" href="{% url 'account_logout' %}">
										<i class="fa-solid fa-right-to-bracket me-2"></i>
										Logout
									</a>
								</li>
								{% endif %}

					
							</ul>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>