blog/urls.py
from django.urls import path
from .views import (

    create_blog_view,
    blog_view,
    CatListView,
    edit_blog_view,
    comment_view,
    delete_post,
    DetailPostView,
    category_list,
    commet_reply_view

)

app_name = 'blog'

urlpatterns = [

    path('create/', create_blog_view, name='create'),
    path('<slug>/edit', edit_blog_view, name='edit'),
    path('category/<category>', CatListView.as_view(), name='category'),
    path('get/category/', category_list, name='category_list'),
    path('<slug:slug>/', DetailPostView.as_view(), name='details'),
    path('comment', comment_view, name='comment'),
    path('comment/reply', commet_reply_view, name='comment_reply'),
    path('delete', delete_post, name='delete_post'),
    path('', blog_view, name='blog'),
]

fitness/urls.py
from django.urls import path
from .views import index_view, search_view, faq_views,  recommendation_view

app_name = "fitness"

urlpatterns = [
    path("", index_view, name="index"),
    path("search/", search_view, name="search"),
    path("faqs/", faq_views, name="faqs"),
    path("recommendation/", recommendation_view, name="recommendation"),
]

site_src/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('account/', include('allauth.urls')),
    path('account/', include('user.urls')),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('', include('fitness.urls')),
    path('blog/', include('blog.urls')),
    path('product/', include('product.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

fitness/models.py
from django.db import models


class TopSearch(models.Model):
    name = models.CharField(max_length=500, null=True)
    search_count = models.IntegerField(default=0)

    def __str__(self):
        return f'{self.name} - Searches: {self.search_count}'


class FrequentlyAskedQuestion(models.Model):
    title = models.CharField(max_length=500)
    content = models.TextField()
    date = models.DateField(auto_now=True, auto_now_add=False)

    def __str__(self):
        return self.title

fitness/forms.py
# forms.py
import django.forms as forms

fitness/views.py
from django.shortcuts import render, redirect
from django.http import JsonResponse
from operator import attrgetter
from django.db.models import Q
from django.core.paginator import EmptyPage, PageNotAnInteger, Paginator
from operator import attrgetter
from product.models import Product, Tag
from blog.models import BlogPost, Category
from .models import TopSearch, FrequentlyAskedQuestion
from .utils import RecommendationSystem, load_user_profiles
from user.models import Profile


def index_view(request):
    all_post = sorted(BlogPost.objects.all(), key=attrgetter('date_updated'), reverse=True)
    product = sorted(Product.objects.all(), key=attrgetter('date_updated'), reverse=True)
    context = {
        'page': 'home',
        'all_post': all_post[:6],
        'all_product': product[:6]
    }
    return render(request, "fitness/index.html", context)


# SEARCH POST FUNCTION
def get_product_queryset(query=None):
    queryset = []
    queries = query.split(" ")
    for q in queries:
        product = Product.objects.all().filter(
            Q(name__icontains=q) |
            Q(price__icontains=q) |
            Q(tag__tag_name__icontains=q) |
            Q(description__icontains=q)
        ).distinct()
        for products in product:
            queryset.append(products)
    return list(set(queryset))

def get_blog_queryset(query=None):
    queryset = []
    queries = query.split(" ")
    for q in queries:
        post = BlogPost.objects.all().filter(
            Q(title__icontains=q) |
            Q(category__category_name__icontains=q) |
            Q(body__icontains=q) 
        ).distinct()
        for post in post:
            queryset.append(post)
    return list(set(queryset))


def get_faq_queryset(query=None):
    queryset = []
    queries = query.split(" ")
    for q in queries:
        service = FrequentlyAskedQuestion.objects.all().filter(
            Q(title__icontains=q) |
            Q(content__icontains=q)
        ).distinct()
        for services in service:
            queryset.append(services)
    return list(set(queryset))


def search_view(request):
    context = {}

    query = ""
    if request.GET:
        query = request.GET.get('q')
        context['query'] = str(query)
        
        top_search, created = TopSearch.objects.get_or_create(name=query)
        top_search.search_count += 1
        top_search.save()
        
        product = sorted(get_product_queryset(query), key=attrgetter('date_updated'), reverse=True)
        post = sorted(get_blog_queryset(query), key=attrgetter('date_updated'), reverse=True)

        # Pagination
        POSTS_PER_PAGE = 9
        page = request.GET.get('page', 1)
        product_paginator = Paginator(product, POSTS_PER_PAGE)
        post_paginator = Paginator(product, POSTS_PER_PAGE)

        try:
            product = product_paginator.page(page)
            post = post_paginator.page(page)
        except PageNotAnInteger:
            product = product_paginator.page(POSTS_PER_PAGE)
            post = post_paginator.page(POSTS_PER_PAGE)
        except EmptyPage:
            product = product_paginator.page(product_paginator.num_pages)
            post = post_paginator.page(post_paginator.num_pages)

        faq = get_faq_queryset(query)
        
        #search result couter
        """if product:
            for items in product:
                search_result, _ = ProductSearch.objects.get_or_create(product=items)
                search_result.search_count += 1
                search_result.save()
        if post:
            for items in post:
                search_result, created = CleanServiceSearch.objects.get_or_create(post=items)
                search_result.search_count += 1
                search_result.save()"""

        context = {
            'all_product': product,
            'post': post,
            'faq_content': faq,
            'query': query,
            'top_search': TopSearch.objects.all()[:6]
        }
    return render(request, 'fitness/search.html', context)


def faq_views(request):
    context = {
        'faq': True,
        'faq_content': FrequentlyAskedQuestion.objects.all(),
    }
    return render(request, "fitness/faqs.html", context)


def recommendation_view(request):
    if request.user.is_authenticated:
        user_id = Profile.objects.get(user=request.user)
        df = load_user_profiles()
        if 'Id' not in df.columns:
            return JsonResponse({'error': 'Invalid data format'}, status=400)
            
        recommender = RecommendationSystem(df)
        collaborative_recommendations = recommender.collaborative_filtering(user_id, num_recommendations=5)
        content_based_recommendations = recommender.content_based_filtering(user_id, num_recommendations=5)
        
        context = {
            'collaborative_nutritional': collaborative_recommendations['Nutritional Preferences'],
            'collaborative_fitness': collaborative_recommendations['Fitness Environment'],
            'content_nutritional': content_based_recommendations['Nutritional Preferences'],
            'content_fitness': content_based_recommendations['Fitness Environment'],
        }
        return render(request, "fitness/recommendation.html", context)
        
    else:
        return redirect('account_login')

templates/fitness/faqs.html
{% extends 'base.html' %}

{% load static %}
{% load humanize %}
{% load hitcount_tags %}
{% block head_title %}FAQs{% endblock %}
{% block content %}

	<style>
        body, .accordion-body{
			background: var(--black);
			background-repeat: no-repeat;
			background-size: cover;
			background-color: var(--black);
			color: var(--yello);
		}
		body::before {
			content: '';
			background: none;
			background-size: cover;
		}
		.accordion-item h2{
			font-size:20px;
		}
	</style>
	<main style="overflow: hidden;" >
		<div class="row justify-content-center container mt-5 mb-5">
            <div class="col-md-6 d-md-none mb-4">
                <div class="container">
                    <img class="w-100" src="{% static 'images/1.jpg' %}" alt="">
                </div>
            </div>
			<div class="col-md-8">
                <div class="container">
                    <h2 class="fw-bold mb-5 h1">Frequently Asked Questions</h2>
                </div>
				<div class="accordion" id="accordionPanelsStayOpenExample">
					{% for faq in faq_content %}
						<div class="accordion-item">
							<h2 class="accordion-header" id="panelsStayOpen-heading{{forloop.counter}}">
								<button class="accordion-button bg-yellow fw-bold" type="button" data-bs-toggle="collapse" data-bs-target="#panelsStayOpen-collapse{{forloop.counter}}" aria-expanded="true" aria-controls="panelsStayOpen-collapse{{forloop.counter}}">
								{{faq.title}}
								</button>
							</h2>
							<div id="panelsStayOpen-collapse{{forloop.counter}}" class="accordion-collapse collapse {% if forloop.counter == 1 %}show{% endif %}" aria-labelledby="panelsStayOpen-heading{{forloop.counter}}">
								<div class="accordion-body">
									{{faq.content}}
								</div>
							</div>
						</div>
					{% endfor %}
				  </div>
			</div>

		</div>
		<div>
			
		
		</div>
	</main>
  
  
{% endblock %}

templates/fitness/index.html
{% extends 'base.html' %}
{% load static %}
{% load humanize %}
{% load hitcount_tags %}
{% block head_title %}Home{% endblock %}
{% block content %}
<style>
    .section1{
        background: url('{% static "img/5.jpeg"%}');
        background-repeat: no-repeat;
        background-size: cover;
        background-color: var(--black);
    }
</style>


<section class="mb-0 pt-5 container-fluid" style="background-color: var(--black); color: var(--yello);">
    <div class="container">
        <h5 class="fw-normal text-center">
            <p>Need Tips and advice?</p>
            <p>Brwose through our blogs on health, fitness and diet</p>
        </h5>
    </div>
    <div class="container">
        <div class="row justify-content-start align-items-center">
            {% for post in all_post %}
            <div class="col-sm-6">
                <div class="card">
                    
                    <div class="card-img">
                        <img class="bd-placeholder-img card-img-top" src="{{post.image_url}}" alt="{{post.title}}">
                    </div>
                    
                    <div class="card-body">
                        <div class="card-content ">
                            <div class="d-sm-flex justify-content-start align-items-center" style="margin-left: 0; padding-left: 0;">
                                <div class="blog-date row justify-content-center text-center align-items-center fw-bold p-2">
                                    <strong class="col-12 p-0">{{ post.date_published.date}}</strong>
                                </div>
                                <div class="d-grid justify-content-start mx-2" style="width: 100%;">

                                    <div class="h6">
                                        {{post.title}}
                                    </div>
                                    <ul class="mx-0 d-flex justify-content-between align-items-center small fs-6" style="width: 100%; padding-left: 0; margin-left: 0;">
                                        <li><i class="fa fa-user"></i> {{post.author}}</li>
                                        <li><i class="fa fa-comment"></i> Comments</li>
                                        <li><i class="fa fa-eye"></i> {% get_hit_count for post %} Views</li>
                                    </ul>
                                </div>
                            </div>
                            <p class="fw-normal">
                                {{post.body|truncatewords:20 |safe}}
                            </p>
                            <a href="{{post.get_absolute_url}}" class="btn btn-danger col-sm-6 col-md-4">Read More</a>
                        </div>
                    </div>
                </div>
            </div>
            {% endfor %}
        </div>
    </div>
</section>

<section class="mb-0 pt-5 container-fluid" style="background-color: var(--black); color: var(--yello);">
    <div class="section container">
        <div class="p-4 p-md-5 mb mb-4rounded"  style="background-color: var(--black); color: var(--yello);" id="sneak-bg">
            <div class="col-md-6 px-0">
              <h1 class="display-4 fst-italic">Fitness & Nutritional Recommendation.</h1>
              <p class="lead my-3">
                Trend Fitness is dedicated to providing professional fitness advice which will include a range from fitness plans to diet plans catered to every individual needs.
              </p>
              <p class="lead mb-0"><a href="{% url "fitness:recommendation" %}" class="text-white fw-bold">continue...</a></p>
            </div>
        </div>
</section>

<section class="mb-0 pt-5 container-fluid" style="background-color: var(--black); color: var(--yello);">
    <div class="container">
        <h5 class="fw-light fs-2 text-center mt-4">
            <div class="fw-bold">Product</div>
            <p>Brwose through our products on health, fitness and diet</p>
        </h5>
    </div>
    <div class="container">
        <div class="row justify-content-start align-items-center">
            {% for post in all_product %}
            <div class="col-sm-6">
                <div class="card">
                    
                    <div class="card-img">
                        <img class="bd-placeholder-img card-img-top" src="{{post.image_url}}" alt="{{post.title}}">
                    </div>
                    
                    <div class="card-body">
                        <div class="card-content ">
                            <div class="d-sm-flex justify-content-start align-items-center" style="margin-left: 0; padding-left: 0;">
                                <div class="blog-date row justify-content-center text-center align-items-center fw-bold p-2">
                                    <strong class="col-12 p-0">{{ post.date_published.date}}</strong>
                                </div>
                                <div class="d-grid justify-content-start mx-2" style="width: 100%;">

                                    <div class="h6">
                                        {{post.name}}
                                    </div>
                                    <ul class="mx-0 d-flex justify-content-between align-items-center small fs-6" style="width: 100%; padding-left: 0; margin-left: 0;">
                                        <li><i class="fa fa-user"></i> {{post.author}}</li>
                                        <li><i class="fa fa-comment"></i> Comments</li>
                                        <li><i class="fa fa-eye"></i> {% get_hit_count for post %} Views</li>
                                    </ul>
                                </div>
                            </div>
                            <p class="fw-normal">
                                {{post.description|truncatewords:20 |safe}}
                            </p>
                            <a href="{{post.get_absolute_url}}" class="btn btn-danger col-sm-6 col-md-4">Read More</a>
                        </div>
                    </div>
                </div>
            </div>
            {% endfor %}
        </div>
    </div>
</section>

<section class="mb-0 pt-5 container-fluid" style="background-color: var(--black); color: var(--yello);">
    <div class="section container-lg d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pb-2 mb-3">
        <div class="row featurette align-items-center">

               
            <div class="col-12 scroll-x-down-el">
                <div class="fs-1 fw-bold text-center">Seamless User Experience</div>                        
                <p class="fs-3 text-center">
                    At TrendFitness, we prioritize a seamless user experience to ensure our users can effortlessly navigate and utilize our platform. Our intuitive interface is designed to be user-friendly, with clear navigation and accessible features that cater to both beginners and advanced users. We understand that your time is valuable, so we've streamlined our processes to minimize hassle and maximize efficiency. Whether you're logging your workouts, tracking your progress, or seeking personalized fitness recommendations, TrendFitness provides a smooth and enjoyable experience every step of the way.
                </p>
            </div>

            <div class="col-12 scroll-x-top-el">
                <div class="fs-1 fw-bold text-center">Fitness Service</div>                        
                <p class="fs-3 text-center">
                    TrendFitness offers comprehensive fitness services tailored to meet the diverse needs of our users. Our platform integrates advanced AI-driven recommendation systems that suggest personalized fitness routines, nutritional plans, and wellness tips. We cover a wide range of fitness goals, including weight loss, muscle gain, endurance, flexibility, and overall health. With access to a variety of fitness environments and resources, including home workout setups, gyms, outdoor activities, and specialized fitness classes, TrendFitness supports your journey to a healthier, fitter lifestyle.
                </p>
            </div> 
            
            <div class="col-12 scroll-x-top-el">
                <div class="fs-1 fw-bold text-center">Commitment to Quality and Expert Support</div>                        
                <p class="fs-3 text-center">
                    We continuously enhance our platform based on user feedback and the latest fitness trends to ensure that we provide the highest quality service. Our team of experts is always ready to assist you, ensuring that you have all the resources and guidance you need to achieve your fitness goals. With TrendFitness, you can be confident that you are receiving the best service in the industry.
                </p>
            </div> 
        </div>
    </div>

    <div>
        <div class="section navbar container-lg d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-1 pb-2 mb-3">
            <div class="row featurette mt-5 align-items-center mb-3">
                <div class="col-md-6 mb-3 scroll-x-down-el scroll-y-top-el">
                    <div class="fs-1 fw-bold text-start">
                        <strong>We Give the best Service</strong>
                    </div>
                    <p class="fs-3 text-start">
                        At TrendFitness, we are committed to delivering the best service to our users. Our dedication to excellence is reflected in our state-of-the-art technology, personalized recommendations, and comprehensive support system.
                    </p>
                </div>

                <div class="col mt-lg-0 mt-sm- fw-bold fs-55 order-lg-last">
                    <div
                        class="h-100 shadow">
                        <!-- style="background-image: url('{% static 'img/dashboard_desktop.png' %}'); background-size:cover; width:100%; height:100%;" -->
                        <div class="">
                            <img style="width: 100%;" src="{% static 'img/1.jpeg' %}" alt="TrendFitness">
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
{% endblock %}

templates/fitness/recommendation.html
{% extends "account/base.html" %}
{% load static %}

{% block head_title %}Recommendation{% endblock %}

{% block content %}
<style>
    body{
        background: url('{% static "img/2.jpeg"%}');
        background-repeat: no-repeat;
        background-size: cover;
        background-color: var(--black);
    }

    .processing_bg {
        position: absolute;
        z-index: 9999999;
        background: var(--black);
        width: 100%;
        height: 100%;
    }

    .processing {
        height: 100%;
        width: 100%;
        position: absolute;
        left: 0;
        top: 0;
        display: flex;
        justify-content: center;
        align-items: center;
    }

    .processing img {
        width: 80px;
        animation: fadeImg 2s linear infinite;
    }


    .show{
        display: block;
        transition: 1s display ease-in-out;
    }
    .card-body ul{
        list-style-type: disc;
    }
</style>

<div class="login-box mt-5 mb-3" style="width: 80%;">
    

  <div class="card" width="500">
    <div class="processing_bg hidden-item" id="processing">
        <div class="processing">
          <img src="{% static 'img/logo.jpeg' %}" alt="loading" />
        </div>
    </div>
    
    
    <div class="mb-3 text-center">
      <div class="mt-4">
        <h3 class="fw-bold fs-h2 navy-blue">Recommendation</h3>
        <p>Recommendation based on overall users and your preference"</p>
      </div>
    </div>
    <div class="card-body row justify-content-center align-items-start">
        <div class="col-md-6">
            <h4>Overall Preferences</h4>

            {% if collaborative_nutritional %}
            <h5>Nutritional Preferences</h5>
            <ul>
                {% for preference in collaborative_nutritional %}
                {% if preference %}
                <li>{{ preference }}</li>
                {% endif %}
                {% endfor %}
            </ul>
            {% endif %}

            {% if collaborative_fitness %}
            <h5>Fitness Environment</h5>
            <ul>
                {% for environment in collaborative_fitness %}
                {% if environment %}
                <li>{{ environment }}</li>
                {% endif %}
                {% endfor %}
            </ul>
            {% endif %}

        </div>

        <div class="col-md-6">            
        <h4>Your Preferences</h4>

        {% if content_nutritional %}
        <h5>Nutritional Preferences</h5>
        <ul>
            {% for preference in content_nutritional %}
            {% if preference %}<li>{{ preference }}</li>{% endif %}            
            {% endfor %}
        </ul>
        {% endif %}

        {% if content_fitness %}
        <h5>Fitness Environment</h5>
        <ul>
            {% for environment in content_fitness %}
            {% if environment %}<li>{{ environment }}</li>{% endif %}
            
            {% endfor %}
        </ul>
        {% endif %}
        </div>
    </div>
  </div>
</div>

<script src="{% static 'js/preloader.js' %}"></script>

{% endblock %}

templates/fitness/search.html
{% extends 'base.html' %}
{% load static %}
{% load humanize %}
{% load hitcount_tags %}
{% block head_title %}Search Result{% endblock %}
{% block content %}

	<style>
		body{
			background: var(--black);
			background-repeat: no-repeat;
			background-size: cover;
			background-color: var(--black);
			color: var(--yello);
		}
		.bg_image{
			height: 300px;
			object-fit: contain;
			overflow: hidden;
		}
		.col-md-6:hover{
			transform: translateY(-20px);
			transition: transform 1s ease-in-out;
		}
	</style>

	<div class="container-fluid" style="overflow-x: hidden;">
		<div class="row">
			<main class="ms-sm-auto px-md-4">

				

				<div class="section container">
                    {% if all_product or post %}
					<h2 class="fw-bold h1 mb-5 mt-5">search result: <i>{{query}}</i></h2>

					<div class="section container">
						<div class="row">
							<div class="col-md-8">
								<div>
									<h3 class="h2 fw-bold">FAQ Search Result: "{{query}}"</h3>
								</div>
								{% if faq_content %}
								<div>
									{% for results in faq_content %}
									<div>
										<a class="fs-5" href="{% url 'fitness:faqs' %}">{{results.title}}?</a>
									</div>
									{% endfor %}
								</div>
								{% else %}
								<div class="container">
									<div class="row">
										 <div class="col-lg-12 col-md-4">
											<div class="card m-auto mb-4 shadow">
												<div class="card-body">
													<h2 class="card-title">No results for FAQ</h2>
													<p>There's no results matching your search: "{{query}}"</p>
												</div>
											</div>
										</div>
									</div>
								</div>
								{% endif %}
							</div>
							<div class="col-md-4 fs-5">
								<h3 class="fw-bold">
									Search keywords
								</h3>
								{% for search in top_search %}
								<a style="transform: translate(0); cursor: pointer;" class="nav-link" href="/search/?q={{search.name}}"><span type="submit" class="mx-3">"{{search.name}}"</span><span>Number of searches {{search.search_count}}</span></a>
								{% endfor %}
							</div>


						</div>
	
					</div>

					

					<div class="row align-items-md-stretch">
                        <h3 class="fw-bold h2 mt-5 mb-4">Product Result: "{{query}}"</h3>
						{% if all_product %}
						<div class="row justify-content-start align-items-center">
							{% for post in all_product %}
							<div class="col-sm-6">
								<div class="card">
									
									<div class="card-img">
										<img class="bd-placeholder-img card-img-top" src="{{post.image_url}}" alt="{{post.title}}">
									</div>
									
									<div class="card-body">
										<div class="card-content ">
											<div class="d-sm-flex justify-content-start align-items-center" style="margin-left: 0; padding-left: 0;">
												<div class="blog-date row justify-content-center text-center align-items-center fw-bold p-2">
													<strong class="col-12 p-0">{{ post.date_published.date}}</strong>
												</div>
												<div class="d-grid justify-content-start mx-2" style="width: 100%;">
				
													<div class="h6">
														{{post.name}}
													</div>
													<ul class="mx-0 d-flex justify-content-between align-items-center small fs-6" style="width: 100%; padding-left: 0; margin-left: 0;">
														<li><i class="fa fa-user"></i> {{post.author}}</li>
														<li><i class="fa fa-comment"></i> Comments</li>
														<li><i class="fa fa-eye"></i> {% get_hit_count for post %} Views</li>
													</ul>
												</div>
											</div>
											<p class="fw-normal">
												{{post.description|truncatewords:20 |safe}}
											</p>
											<a href="{{post.get_absolute_url}}" class="btn btn-danger col-sm-6 col-md-4">Read More</a>
										</div>
									</div>
								</div>
							</div>
							{% endfor %}
							
						</div>
						{% else %}
								<div class="container">
									<div class="row">
										 <div class="col-lg-12 col-md-4">
											<div class="card m-auto mb-4 shadow">
												<div class="card-body">
													<h2 class="card-title">No results found for Product</h2>
													<p>There's no results matching your search: "{{query}}"</p>
												</div>
											</div>
										</div>
									</div>
								</div>
						{% endif %}
					</div>

					<div class="blog-pagination " aria-label="Pagination">
						<a class="btn btn-outline-yellow {% if not all_product.has_previous  %}disabled {% endif %}"{% if all_product.has_previous  %}href="?{% if query %}q={{query}}&{% endif %}page={{all_product.previous_page_number}}"{% else %} href="" tabindex="-1"{% endif %}>Older</a>

						<a class="btn btn-outline-secondary {% if not all_product.has_next %}disabled {% endif %}" {% if all_product.has_next  %} href="?{% if query %}q={{query}}&{% endif %}page={{all_product.next_page_number}}"{% else %} href="" tabindex="-1"{% endif %} >Newer</a>
					</div>

                    <div class="row align-items-md-stretch mt-5 mb-5">
                        <div class="article_home_right_1 clearfix">
                          <h3 class="h2 fw-bold">Article Result: "{{query}}"</h3>

						  {% if post %}
      
                          <div class="row justify-content-start align-items-center">
							{% for post in post %}
							<div class="col-sm-6">
								<div class="card">
									
									<div class="card-img">
										<img class="bd-placeholder-img card-img-top" src="{{post.image_url}}" alt="{{post.title}}">
									</div>
									
									<div class="card-body">
										<div class="card-content ">
											<div class="d-sm-flex justify-content-start align-items-center" style="margin-left: 0; padding-left: 0;">
												<div class="blog-date row justify-content-center text-center align-items-center fw-bold p-2">
													<strong class="col-12 p-0">{{ post.date_published.date}}</strong>
												</div>
												<div class="d-grid justify-content-start mx-2" style="width: 100%;">
				
													<div class="h6">
														{{post.name}}
													</div>
													<ul class="mx-0 d-flex justify-content-between align-items-center small fs-6" style="width: 100%; padding-left: 0; margin-left: 0;">
														<li><i class="fa fa-user"></i> {{post.author}}</li>
														<li><i class="fa fa-comment"></i> Comments</li>
														<li><i class="fa fa-eye"></i> {% get_hit_count for post %} Views</li>
													</ul>
												</div>
											</div>
											<p class="fw-normal">
												{{post.description|truncatewords:20 |safe}}
											</p>
											<a href="{{post.get_absolute_url}}" class="btn btn-danger col-sm-6 col-md-4">Read More</a>
										</div>
									</div>
								</div>
							</div>
							{% endfor %}
							
						</div>
						  {% else %}
								<div class="container">
									<div class="row">
										 <div class="col-lg-12 col-md-4">
											<div class="card m-auto mb-4 shadow">
												<div class="card-body">
													<h2 class="card-title">No results for Services</h2>
													<p>There's no results matching your search: "{{query}}"</p>
												</div>
											</div>
										</div>
									</div>
								</div>
						  {% endif %}
                      </div>

					  <div class="blog-pagination " aria-label="Pagination">
						<a class="btn btn-outline-yellow {% if not post.has_previous  %}disabled {% endif %}"{% if post.has_previous  %}href="?{% if query %}q={{query}}&{% endif %}page={{post.previous_page_number}}"{% else %} href="" tabindex="-1"{% endif %}>Older</a>

						<a class="btn btn-outline-secondary {% if not post.has_next %}disabled {% endif %}" {% if post.has_next  %} href="?{% if query %}q={{query}}&{% endif %}page={{post.next_page_number}}"{% else %} href="" tabindex="-1"{% endif %} >Newer</a>
					</div>
      
                    </div>
                    {% else %}
                    <div class="container">
                        <div class="row">
                             <div class="">
                                <div class="card m-auto mb-4 shadow">
                                    <div class="card-body d-grid fs-3">
                                        <h2 class="card-title">No results</h2>
                                        <p>There's no results matching your search: "{{query}}"</p>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>

                    {% endif %}
					
				</div>

			</main>
		</div>
	</div>
{% endblock %}